### PR TITLE
Link instead of rename

### PR DESCRIPTION
**Pull request by dominikl**
Instead of renaming the images, they are now copied into a subdirectory called `import` with the proper `C` `Z` `T` naming pattern (see the generated `scripts/import/renameCommands.sh` script). I also changed the channel pattern from `C<0-1>` to use the proper channel names, e. g. `C<Cep192,EB3>`, might need that later to rename the channels (unfortunately they are still imported as channel `0`, `1`, etc. so that will need an extra renaming step later).

/cc @sbesson Could you run the `renameCommands.sh` script? I would then try to import the files on the testing server.

### CODE REVIEW

**Comment by dominikl** [comment]
Ah sorry, just realized I have to put everything in quotes, as there are file names with whitespaces. Hold off for a bit...

**Comment by sbesson** [comment]
Very nice. I would almost vote for completely separating the root folder for the original author submission (`20180709-ftp`) from the renamed data folder for import rather than using an `import` subfolder e.g. `20180731-renamed` or similar so that we have some date versioining allowing us to trace back the generation of the data using these scripts if needed.

**Comment by sbesson** [comment]
Had a quick discussion/hacking session with @dominikl. As we are doing in-place import using symlinks it might be sufficient to symlink the original data i.e.:

```
$ mkdir test && cd test
$ ln -s /uod/idr/filesets/idr0045-reichmann/20180709-ftp/Figure01A/Embryo1.EGFP.Cam_Right_00150.tif Embryo1_CEGFP.Cam_Right_T150.tif
$ ln -s /uod/idr/filesets/idr0045-reichmann/20180709-ftp/Figure01A/Embryo1.mCherry.Cam_Right_00150.tif Embryo1_CmCherry.Cam_Right_T150.tif
$ echo "Embryo1_C<EGFP,mCherry>.Cam_Right_T150.tif" > Embryo1.pattern
$ /opt/omero/server/OMERO.server/bin/omero import -f Embryo1.pattern
```

Advantage of the solution above is it saves the copy of the bytes so the operation is pretty cheap and can be done as many times as needed. @dominikl will try and adjust the scripts to use `ln -s` so that we can test tomorrow.

**Comment by dominikl** [comment]
Also renamed the script to `createPatternFiles.sh`, hope then it's a bit more obvious what the script actually does.

**Comment by dominikl** [comment]
Could you try again @sbesson ? The script now needs to run in the idr0045 "root" directory (`/uod/idr/filesets/idr0045-reichmann` or whatever this path is in the original filesystem).

**Comment by sbesson** [comment]
With the latest changes, the script executes in ~30s and creates 24682 valid symlinks and 336 pattern files. Testing a few of these files using `bin/omero import -f` works as expected as filesets are detected. Merging and I will execute the script on the shared NFS server so that @dominikl can try a first import of the dataset into the testing resource.

**Pull request merged**
